#!/bin/bash

file="hello"
owner="guillaume"
new_owner="betty"

current_owner=$(stat -c %U "$file")

if [ "$current_owner" = "$owner" ]; then
    chown "$new_owner" "$file"
    echo "Owner of $file changed to $new_owner"
else
    echo "File $file is not owned by $owner"
fi
